[pytest]
# List of directories to collect tests from
testpaths =
    quackcore/tests
    quackverse/tests
    quackster/tests
    tests/integration

# Test file matching pattern
python_files = test_*.py

# Configure pytest modules
filterwarnings = error

# Add the src directories to Python's import path
pythonpath =
    quackcore/src
    quackverse/src
    quackster/src

# Display extra test information
addopts =
    -v
    --import-mode=importlib