"""
Live, non-mocked integration tests for FFmpegIntegration.

Unlike test_service.py (which mocks `ffmpeg_zeo` itself to test
FFmpegIntegration's own logic in isolation), these tests run the real
`ffmpeg`/`ffprobe` binaries via the real `ffmpeg-zeo` package end to end:
generate a synthetic media file with ffmpeg's own `lavfi` test source, then
probe/thumbnail/transcode/extract-audio/convert it through the wrapper and
assert on real output files and real ffprobe-derived metadata.

Skipped automatically (not failed) when ffmpeg-zeo is not installed (i.e. the
`ffmpeg` extra was not installed) or when no `ffmpeg`/`ffprobe` binary is
resolvable on this machine -- `ffmpeg_zeo.resolve_binaries()` is exactly the
same resolution path `FFmpegIntegration.initialize()` itself uses, so a skip
here means the wrapper cannot be initialized in this environment either
(nothing to test, not a failure of the wrapper).
"""

import shutil
import subprocess
from pathlib import Path

import pytest

from zeo_core.integrations.ffmpeg.service import FFmpegIntegration

ffmpeg_zeo = pytest.importorskip("ffmpeg_zeo", reason="ffmpeg-zeo extra not installed")

_FFMPEG_BIN = shutil.which("ffmpeg")
_FFPROBE_BIN = shutil.which("ffprobe")

pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(
        _FFMPEG_BIN is None or _FFPROBE_BIN is None,
        reason="ffmpeg/ffprobe binary not found on PATH",
    ),
]


@pytest.fixture
def sample_video(tmp_path: Path) -> Path:
    """A short synthetic video+audio file generated by ffmpeg's own lavfi source."""
    path = tmp_path / "sample.mp4"
    assert _FFMPEG_BIN is not None  # narrowed by the module-level skipif above
    subprocess.run(  # noqa: S603 -- fixed argv, resolved absolute binary path, test-only, no shell
        [
            _FFMPEG_BIN,
            "-hide_banner",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=1:size=160x120:rate=5",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=1",
            "-c:v",
            "libx264",
            "-c:a",
            "aac",
            "-y",
            str(path),
        ],
        check=True,
        capture_output=True,
    )
    return path


@pytest.fixture
def integration(tmp_path: Path) -> FFmpegIntegration:
    """A real, ready FFmpegIntegration -- real ffmpeg-zeo binary resolution,
    config loading bypassed.

    `zeo_core.core.fs.service.standalone` is a module-level singleton whose
    sandbox `base_dir` is captured from `Path.cwd()` at its OWN first
    construction (whichever test file/fixture happens to import it first in
    the process), not re-derived per call -- so `monkeypatch.chdir` in this
    fixture has no effect on it once any earlier test in the same pytest
    process has already touched `standalone`. `initialize()`'s config-loading
    step (`FFmpegConfigProvider.load_config` -> `BaseConfigProvider.
    load_config` -> `standalone.get_file_info`) is exactly the affected path,
    so -- matching pandoc's own test convention of never exercising a real
    on-disk config file either (see pandoc/test_pandoc_integration_full.py) --
    this fixture skips initialize() and drives the two steps this test module
    actually cares about directly: a real FFmpegConfig (no file I/O) and a
    real `ffmpeg_zeo.resolve_binaries()` call (real subprocess discovery, not
    mocked), which is the same binary-resolution path initialize() itself
    uses.
    """
    from ffmpeg_zeo import resolve_binaries

    from zeo_core.integrations.ffmpeg.config import FFmpegConfig

    integ = FFmpegIntegration()
    integ.config = FFmpegConfig(output_dir=str(tmp_path / "output"))
    binary_info = resolve_binaries()
    integ._ffmpeg_bin = str(binary_info.ffmpeg)  # noqa: SLF001 -- test fixture wiring the same private state initialize() sets, deliberately bypassing initialize() itself per the docstring above
    integ._ffprobe_bin = str(binary_info.ffprobe)  # noqa: SLF001 -- see above
    integ._initialized = True  # noqa: SLF001 -- see above
    return integ


def test_fixture_resolved_real_binaries(integration: FFmpegIntegration) -> None:
    """Sanity check on the `integration` fixture: real binary paths, real files."""
    assert integration.is_available()
    ffmpeg_bin = integration.get_ffmpeg_binary()
    assert ffmpeg_bin is not None
    assert Path(ffmpeg_bin).exists()


def test_initialize_end_to_end_in_process_cwd() -> None:
    """Exercise the real initialize() path (config load + binary resolve)
    without chdir/monkeypatch, by placing the config file inside
    `zeo_core.core.fs.service.standalone`'s actual sandboxed base_dir
    (`Path.cwd()` at process start, i.e. wherever pytest itself was invoked
    from) rather than fighting that module-level singleton's cwd capture --
    see the `integration` fixture's docstring for why chdir does not work
    here once any earlier test has touched `standalone`.
    """
    import shutil
    import uuid

    # Both the config file AND the configured output_dir must be relative
    # paths under standalone's sandboxed base_dir (the zeocore repo root) --
    # an absolute tmp_path-based output_dir hits the identical
    # path_outside_base_dir rejection the config path would. A uuid-suffixed
    # name keeps this collision-free with any real repo contents.
    unique = uuid.uuid4().hex
    config_name = f"zeo_ffmpeg_live_test_{unique}.yaml"
    output_dir_name = f"zeo_ffmpeg_live_test_output_{unique}"
    config_path = Path.cwd() / config_name
    output_dir_path = Path.cwd() / output_dir_name
    try:
        config_path.write_text(f"ffmpeg:\n  output_dir: ./{output_dir_name}\n")

        integ = FFmpegIntegration(config_path=config_name)
        result = integ.initialize()

        assert result.success, f"initialize() failed: {result.error}"
        assert integ.is_available()
        ffmpeg_bin = integ.get_ffmpeg_binary()
        assert ffmpeg_bin is not None
        assert Path(ffmpeg_bin).exists()
    finally:
        config_path.unlink(missing_ok=True)
        shutil.rmtree(output_dir_path, ignore_errors=True)


def test_probe_real_file(integration: FFmpegIntegration, sample_video: Path) -> None:
    result = integration.probe(str(sample_video))

    assert result.success, result.error
    assert result.content is not None
    assert result.content["has_video"] is True
    assert result.content["has_audio"] is True
    assert result.content["width"] == 160
    assert result.content["height"] == 120
    assert result.content["video_codec"] == "h264"
    assert result.content["duration_seconds"] == pytest.approx(1.0, abs=0.5)


def test_probe_missing_file_errors(
    integration: FFmpegIntegration, tmp_path: Path
) -> None:
    result = integration.probe(str(tmp_path / "does_not_exist.mp4"))

    assert not result.success
    assert result.error is not None
    assert "ffprobe failed" in result.error


def test_thumbnail_produces_real_file(
    integration: FFmpegIntegration, sample_video: Path, tmp_path: Path
) -> None:
    out = tmp_path / "thumb.jpg"

    result = integration.thumbnail(str(sample_video), str(out), time=0.1)

    assert result.success, result.error
    assert result.content == str(out)
    assert out.exists()
    assert out.stat().st_size > 0


def test_transcode_h264_produces_real_file(
    integration: FFmpegIntegration, sample_video: Path, tmp_path: Path
) -> None:
    out = tmp_path / "transcoded.mp4"

    result = integration.transcode_h264(
        str(sample_video), str(out), crf=30, preset="ultrafast"
    )

    assert result.success, result.error
    assert out.exists()

    probe_result = integration.probe(str(out))
    assert probe_result.success
    assert probe_result.content is not None
    assert probe_result.content["video_codec"] == "h264"


def test_extract_audio_produces_real_file(
    integration: FFmpegIntegration, sample_video: Path, tmp_path: Path
) -> None:
    out = tmp_path / "audio.aac"

    result = integration.extract_audio(str(sample_video), str(out), codec="copy")

    assert result.success, result.error
    assert out.exists()
    assert out.stat().st_size > 0


def test_convert_produces_real_file(
    integration: FFmpegIntegration, sample_video: Path, tmp_path: Path
) -> None:
    out = tmp_path / "converted.mkv"

    result = integration.convert(str(sample_video), str(out))

    assert result.success, result.error
    assert out.exists()

    probe_result = integration.probe(str(out))
    assert probe_result.success
    assert probe_result.content is not None
    assert probe_result.content["has_video"] is True
    assert probe_result.content["has_audio"] is True


def test_metrics_accumulate_across_calls(
    integration: FFmpegIntegration, sample_video: Path, tmp_path: Path
) -> None:
    integration.thumbnail(str(sample_video), str(tmp_path / "t1.jpg"), time=0.1)
    integration.thumbnail(str(sample_video), str(tmp_path / "t2.jpg"), time=0.2)

    assert integration.metrics.total_attempts == 2
    assert integration.metrics.successful_renders == 2
    assert integration.metrics.failed_renders == 0
